-- Ajout des champs "Caracteristiques produit" (safe / idempotent)
-- MySQL 8.0+ (IF NOT EXISTS).
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS material VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS style VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS occasion VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `cut` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS finishes VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS inspiration VARCHAR(255) NULL;

